name: fantasyleague-export
services:
- environment_slug: php
  github:
    branch: main
    deploy_on_push: true
    repo: https://github.com/sneakersgames/fantasyleague-export.git
  name: fantasyleague-export
